apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: xbridge-fe-prd

resources:
  - ../../base
  - httproute.yaml

patches:
  - patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/env/0"
        value:
          name: VITE_ENV
          value: "PROD"
    target:
      kind: Deployment
      name: xbridge-frontend