# bootstrap_address = [
#   "12D3KooWESbrSPohuw87dQDbJCB8qeeNgJsFD3ahkea3cu41m7bG",
#   "/ip4/172.16.8.135/tcp/3333",
# ]

# BSC Testnet
[[chain_configs]]
## The block at which history replay should start.
chain_gateway_block_deployed = 36696045

## When replaying history, we replay dispatches first, then relays. In order to do this
## on old blocks in a reasonable time, we should not only start just before the message to be
## replayed, but stop just after. This allows us to stop at a particular block when catching
## up
## to_block_number = 4000000

## RPC URL to talk to for this chain.
rpc_url = "https://bsc-prebsc-dataseed.bnbchain.org"
## The (EVM) address of the chain gateway contract
##  - events from anywhere else will be ignored.
##  - relay requests for this chain id will be relayed to this contract.
chain_gateway_address = "0xa9A14C90e53EdCD89dFd201A3bF94D867f8098fE"
## If this key is absent, we submit relay transactions with "enough" gas per eth_estimateGas().
## Most chains seem to have problems with this, and so this key exists to allow you to
## submit legacy_gas_estimation_percent percent of the estimated gas, so as to ensure that
## relay txns don't run out of gas. A value of 130-150 seems to work for coin transfers.
gas_estimation_percent = 130
## If this key is present, we delay scanning a block until N blocks ahead of it have been
## produced, to give some chains time to propagate block data to the nodes from which we are
## attempting to read them.
## scan_behind_blocks = 1

## If this is set true (Zilliqa 1 again!), we assume that any block we see is final.
## Otherwise (every other chain), we ask for the latest finalized block and scan that.
## block_instant_finality = true

## Normally, we use eth_getFilterLogs() to fetch relay events for processing.
## Some chains (Zilliqa 1) will sometimes get into a state where they return [] for eth_getFilterLogs()
## regardless of the actual emitted logs for a block. This obviously confuses us.
## Worse, eth_getBlockReceipts() has the same problem.
## So, if you set this to true, we will call eth_getBlock() and then iterate through each transaction
## fetching the receipt and scanning it for relevant logs. This is slow, but at least it works ..
## use_get_transactions = true

## Defines the exception set - events that should be treated like other events.
## This is used for exceptional reprocessing of bridge transactions that have been generated
## as the result of bugs and need to be reprocessed.
## Annoyingly, the exceptions must be single-line as otherwise the toml parser will complain.
##exceptions = [
## { transaction_id = "0xa4738bffe20fff0d71d449685ad8e252dc2645948034d0e1ca12772422744b0c", block_hash="0xb71c1c134044480d1ffd1b7822382769b160b38729a27b35d14c5093b93911c9", block_number=46770995, chain_id="0x61", replacement_bytes="0x00000000000000000000000041823941d00f47ea1a98d75586915bf828f4a038000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000f4240000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000e41a90748a000000000000000000000000000000000000000000000000000000000000006100000000000000000000000036b8a9cd6bf9bfa5984093005cf81cafb1bf06f7000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000600000000000000000000000009be4dcfb335a263c65a8a763d55710718bbdb416000000000000000000000000b85ff091342e2e7a7461238796d5224fa81ca556000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000", replacement_chainid="0x000000000000000000000000000000000000000000000000000000000000814d" }]


# BSC Mainnet
# [[chain_configs]]
# chain_gateway_block_deployed = 0
# rpc_url = "https://binance.llamarpc.com"
# chain_gateway_address = "0x2114e979b7CFDd8b358502e00f50Fd5f7787Fe63"

# [[chain_configs]]
# rpc_url = "http://localhost:8545"
# chain_gateway_address = "0x4212b368876a54F99c741C8B5b64be2e52a6956b"

# [[chain_configs]]
# rpc_url = "http://localhost:8546"
# chain_gateway_address = "0x4212b368876a54F99c741C8B5b64be2e52a6956b"

# Zilliqa Testnet
[[chain_configs]]
chain_gateway_block_deployed = 6542681
rpc_url = "https://dev-api.zilliqa.com"
chain_gateway_address = "0x7370e69565BB2313C4dA12F9062C282513919230"
block_instant_finality = true
gas_estimation_percent = 130

[[chain_configs]]
# Base sepolia
rpc_url = "https://sepolia.base.org"
chain_gateway_address = "0xaa084F6EE63B6f5F4c9F84cDbEC3C690DA00d56D"
gas_estimation_percent = 150
chain_gateway_block_deployed = 20931700
# to_block_number=


# Zilliqa Mainnet
# [[chain_configs]]
# chain_gateway_block_deployed = 0
# rpc_url = "https://api.zilliqa.com"
# chain_gateway_address = "0xE76669e1cCc150194eB92581baE79Ef6fa0E248E"
# block_instant_finality = true
# legacy_gas_estimation = true
