name: "CI for Product Bridge - synthetic change for testing"

on:
  push: {}

jobs:
  testing:
    runs-on: ubuntu-latest
    name: "Bridge Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install nodes packages
        run: npm ci
        working-directory: bridge-web

      - name: Check bridge-web build
        run: npm run build
        working-directory: bridge-web

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Foundry tests
        run: forge test --disable-block-gas-limit
        working-directory: smart-contracts
